[package]
org = "ballerina"
name = "return_policy_agreement"
version = "0.1.0"
distribution = "2201.8.4"

[[dependency]]
org = "ballerinax"
name = "docusign.dsclick"
version = "1.0.0"
repository = "local"

[build-options]
observabilityIncluded = true
